### ISSUE TITLE
Create ClickUpClient to avoid boilerplate on every method

### ISSUE THREAD

**Issue by dochoss** [fenterbug/Boson.ClickUp.Net#7]
On each method that accesses the API you're doing `client.DefaultRequestHeaders.Add("Authorization", ApiKeys.PersonalToken);`  Since this will be required for every method, it might be worth adding that inside a wrapper for the HttpClient, something like `ClickUpClient`.  Might even be good to do that so you can interface it and be able to build a repository pattern on it.  More work, but more in line with modern patterns, I think.

**Comment by fenterbug** [comment]
I totally agree. I'd guess about 80% of the code in each method is boilerplate. Different return types. Different parameters (possibly addressed in issue #8). Different REST endpoints and http actions. But really, most of the code is identical. This would be a good issue for someone to tackle. (I know that's me, but I'm trying to keep my tone general in the spirit of having an open community project.)
